### ISSUE TITLE
Import example incorrect in README.md

### ISSUE THREAD

**Issue by geekoala** [vmalloc/Flask-Loopback#11]
Great tool!
If I use correctly, I think there is a mistake in README.md.
```python
from flask.ext.loopback import FlaskLoopback
```
Should the above be the following?
```python
from flask_loopback.flask_loopback import FlaskLoopback
```

**Comment by vmalloc** [comment]
@geekoala that's correct. The `.ext.` syntax used to be correct, but has recently been deprecated by Flask
